version: '3.8'

services:
  aiopslab-viewer:
    build: .
    container_name: aiopslab-viewer
    ports:
      - "3000:3000"    # HTTP
      - "3443:3443"    # HTTPS
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - RUNS_PATH=/app/runs
      - DATABASE_PATH=/app/runs.db
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - LOG_LEVEL=info
    volumes:
      # Mount runs directory for persistent data
      - ./runs:/app/runs
      # Mount database for persistent storage
      - ./runs.db:/app/runs.db
      # Mount environment file (optional)
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: aiopslab-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - aiopslab-viewer
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: aiopslab-network
